# language: php
before_commands:
    - "composer install --no-dev --prefer-source"

tools:
    external_code_coverage:
        timeout: 600
    php_code_sniffer:
        enabled: false
    php_cpd:
        enabled: true
        filter:
            paths: ["src/*"]
    php_loc:
        enabled: true
        filter:
            paths: ["src/*"]
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml.dist
            design_rules: { eval_expression: false }
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        filter:
            paths: ["src/*"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "tests/PhpParser/*"]
    sensiolabs_security_checker: false
